# Generated by Django 3.0.6 on 2020-05-31 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField()),
                ('post_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
