# Generated by Django 3.0.6 on 2020-06-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200531_2307'),
        ('notification', '0002_auto_20200531_2330'),
    ]

    operations = [
    ]
